[0m06:48:39.630853 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab30cc7d2b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab30cc7c110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab30cc7f800>]}


============================== 06:48:39.634169 | e6a2c2ba-7bd0-40c3-93ae-c2ccc5a78085 ==============================
[0m06:48:39.634169 [info ] [MainThread]: Running with dbt=1.9.2
[0m06:48:39.634826 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/patrick/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m06:48:39.635399 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/patrick/llm_pricing/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m06:48:39.636368 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.08083847, "process_in_blocks": "10984", "process_kernel_time": 0.167867, "process_mem_max_rss": "89132", "process_out_blocks": "8", "process_user_time": 1.493722}
[0m06:48:39.636854 [debug] [MainThread]: Command `dbt run` failed at 06:48:39.636738 after 0.08 seconds
[0m06:48:39.637300 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab30cd61fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab30d54b140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab30ce2ac60>]}
[0m06:48:39.637724 [debug] [MainThread]: Flushing usage events
[0m06:48:40.399987 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m06:49:11.314009 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72df357f8f80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72df35d5c620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72df34d843b0>]}


============================== 06:49:11.317426 | aeb2392b-6354-48b5-bf7a-d934d2f20190 ==============================
[0m06:49:11.317426 [info ] [MainThread]: Running with dbt=1.9.2
[0m06:49:11.318307 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/patrick/llm_pricing', 'debug': 'False', 'version_check': 'True', 'log_path': '/home/patrick/llm_pricing/logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m06:49:11.335450 [error] [MainThread]: Encountered an error:
Runtime Error
  Credentials in profile "elasticity_project", target "dev" invalid: 'schemas_and_paths' is a required property
[0m06:49:11.336490 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.097961344, "process_in_blocks": "0", "process_kernel_time": 0.15882, "process_mem_max_rss": "90500", "process_out_blocks": "16", "process_user_time": 1.479328}
[0m06:49:11.337003 [debug] [MainThread]: Command `dbt run` failed at 06:49:11.336875 after 0.10 seconds
[0m06:49:11.337438 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72df3597ade0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72df35d5c620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72df34bb82f0>]}
[0m06:49:11.337885 [debug] [MainThread]: Flushing usage events
[0m06:49:12.143818 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m06:50:23.988009 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e046a3bc200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e04674f1eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e0468cc7470>]}


============================== 06:50:23.991536 | 84e73854-16ba-46be-adfc-0cff694739fb ==============================
[0m06:50:23.991536 [info ] [MainThread]: Running with dbt=1.9.2
[0m06:50:23.992521 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/home/patrick/llm_pricing', 'log_path': '/home/patrick/llm_pricing/logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m06:50:24.010534 [error] [MainThread]: Encountered an error:
Runtime Error
  Credentials in profile "elasticity_project", target "dev" invalid: 'schema_directory' is a required property
[0m06:50:24.011862 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.09857501, "process_in_blocks": "0", "process_kernel_time": 0.174529, "process_mem_max_rss": "90312", "process_out_blocks": "8", "process_user_time": 1.503949}
[0m06:50:24.012438 [debug] [MainThread]: Command `dbt run` failed at 06:50:24.012316 after 0.10 seconds
[0m06:50:24.012953 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e0467105a60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e0466bff8c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e0466bff5f0>]}
[0m06:50:24.013565 [debug] [MainThread]: Flushing usage events
[0m06:50:24.949871 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m06:51:12.362048 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7058d3c3b2c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7058d286a390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7058d2869d30>]}


============================== 06:51:12.365523 | e3be1c08-5dff-4719-8ac1-e9777919fe39 ==============================
[0m06:51:12.365523 [info ] [MainThread]: Running with dbt=1.9.2
[0m06:51:12.366223 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/patrick/llm_pricing', 'fail_fast': 'False', 'version_check': 'True', 'log_path': '/home/patrick/llm_pricing/logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m06:51:12.528161 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'e3be1c08-5dff-4719-8ac1-e9777919fe39', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7058d3318da0>]}
[0m06:51:12.615322 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'e3be1c08-5dff-4719-8ac1-e9777919fe39', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7058d22d9940>]}
[0m06:51:12.616175 [info ] [MainThread]: Registered adapter: sqlite=1.9.0
[0m06:51:12.709832 [debug] [MainThread]: checksum: 12b12750b70de726cfd89136b8e24afc3f3e77597a97bff40ab7e5f9b39d5e18, vars: {}, profile: , target: , version: 1.9.2
[0m06:51:12.710509 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m06:51:12.710938 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'e3be1c08-5dff-4719-8ac1-e9777919fe39', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7058d1a30320>]}
[0m06:51:13.761290 [error] [MainThread]: Encountered an error:
Compilation Error
  Model 'model.elasticity_project.product_elasticity' (models/product_elasticity.py) depends on a node named 'orders' which was not found
[0m06:51:13.762542 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 1.4765232, "process_in_blocks": "328", "process_kernel_time": 0.183947, "process_mem_max_rss": "100768", "process_out_blocks": "16", "process_user_time": 2.857181}
[0m06:51:13.763332 [debug] [MainThread]: Command `dbt run` failed at 06:51:13.763205 after 1.48 seconds
[0m06:51:13.763781 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7058d1dd3bf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7058d1662ff0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7058d1662f90>]}
[0m06:51:13.764248 [debug] [MainThread]: Flushing usage events
[0m06:51:14.717037 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m06:55:37.920077 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76c047e16db0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76c04823b980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76c04833b080>]}


============================== 06:55:37.923561 | 8f03f002-f176-4f9f-9075-2c83fe622e4c ==============================
[0m06:55:37.923561 [info ] [MainThread]: Running with dbt=1.9.2
[0m06:55:37.924323 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/patrick/llm_pricing', 'log_path': '/home/patrick/llm_pricing/logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m06:55:38.088764 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '8f03f002-f176-4f9f-9075-2c83fe622e4c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76c048504110>]}
[0m06:55:38.176918 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '8f03f002-f176-4f9f-9075-2c83fe622e4c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76c047a99af0>]}
[0m06:55:38.177807 [info ] [MainThread]: Registered adapter: sqlite=1.9.0
[0m06:55:38.269341 [debug] [MainThread]: checksum: 12b12750b70de726cfd89136b8e24afc3f3e77597a97bff40ab7e5f9b39d5e18, vars: {}, profile: , target: , version: 1.9.2
[0m06:55:38.270016 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m06:55:38.270436 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '8f03f002-f176-4f9f-9075-2c83fe622e4c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76c0478cbb00>]}
[0m06:55:39.471024 [error] [MainThread]: Encountered an error:
Compilation Error
  Model 'model.elasticity_project.product_elasticity' (models/product_elasticity.py) depends on a node named 'orders' which was not found
[0m06:55:39.472260 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 1.6268378, "process_in_blocks": "0", "process_kernel_time": 0.190927, "process_mem_max_rss": "102292", "process_out_blocks": "16", "process_user_time": 2.976872}
[0m06:55:39.472797 [debug] [MainThread]: Command `dbt run` failed at 06:55:39.472683 after 1.63 seconds
[0m06:55:39.473240 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76c0472a3c20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76c048b622a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76c047259970>]}
[0m06:55:39.473669 [debug] [MainThread]: Flushing usage events
[0m06:55:40.340392 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m06:56:11.490698 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71dea1daee70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71dea1d871d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71dea1c16db0>]}


============================== 06:56:11.494157 | 29889234-2336-4d96-ab7c-653342c4f262 ==============================
[0m06:56:11.494157 [info ] [MainThread]: Running with dbt=1.9.2
[0m06:56:11.494833 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': '/home/patrick/llm_pricing/logs', 'fail_fast': 'False', 'profiles_dir': '/home/patrick/llm_pricing', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m06:56:11.657571 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '29889234-2336-4d96-ab7c-653342c4f262', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71dea30286e0>]}
[0m06:56:11.745312 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '29889234-2336-4d96-ab7c-653342c4f262', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71dea1307710>]}
[0m06:56:11.746207 [info ] [MainThread]: Registered adapter: sqlite=1.9.0
[0m06:56:11.839814 [debug] [MainThread]: checksum: 12b12750b70de726cfd89136b8e24afc3f3e77597a97bff40ab7e5f9b39d5e18, vars: {}, profile: , target: , version: 1.9.2
[0m06:56:11.840516 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m06:56:11.840951 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '29889234-2336-4d96-ab7c-653342c4f262', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71dea0f0df70>]}
[0m06:56:13.092232 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.elasticity_project.models
[0m06:56:13.104799 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '29889234-2336-4d96-ab7c-653342c4f262', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71dea0d82d20>]}
[0m06:56:13.177013 [debug] [MainThread]: Wrote artifact WritableManifest to /home/patrick/llm_pricing/target/manifest.json
[0m06:56:13.179710 [debug] [MainThread]: Wrote artifact SemanticManifest to /home/patrick/llm_pricing/target/semantic_manifest.json
[0m06:56:13.192850 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '29889234-2336-4d96-ab7c-653342c4f262', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71dea08bcd10>]}
[0m06:56:13.193383 [info ] [MainThread]: Found 3 models, 1 source, 413 macros
[0m06:56:13.193787 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '29889234-2336-4d96-ab7c-653342c4f262', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71dea0b3eba0>]}
[0m06:56:13.195794 [info ] [MainThread]: 
[0m06:56:13.196251 [info ] [MainThread]: Concurrency: 1 threads (target='dev')
[0m06:56:13.196626 [info ] [MainThread]: 
[0m06:56:13.197201 [debug] [MainThread]: Acquiring new sqlite connection 'master'
[0m06:56:13.203459 [debug] [ThreadPool]: Acquiring new sqlite connection 'list_/home/patrick/llm_pricing/example.db'
[0m06:56:13.304845 [debug] [ThreadPool]: Using sqlite connection "list_/home/patrick/llm_pricing/example.db"
[0m06:56:13.305450 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db: BEGIN
[0m06:56:13.305897 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m06:56:13.306665 [debug] [ThreadPool]: SQL status: OK in 0.001 seconds
[0m06:56:13.307032 [debug] [ThreadPool]: Using sqlite connection "list_/home/patrick/llm_pricing/example.db"
[0m06:56:13.307440 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db: /* {"app": "dbt", "dbt_version": "1.9.2", "profile_name": "elasticity_project", "target_name": "dev", "connection_name": "list_/home/patrick/llm_pricing/example.db"} */

        pragma database_list
    
[0m06:56:13.307853 [debug] [ThreadPool]: SQL status: OK in 0.000 seconds
[0m06:56:13.309266 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db: ROLLBACK
[0m06:56:13.309657 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db: Close
[0m06:56:13.311258 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_/home/patrick/llm_pricing/example.db, now list_/home/patrick/llm_pricing/example.db_main)
[0m06:56:13.322728 [debug] [ThreadPool]: Using sqlite connection "list_/home/patrick/llm_pricing/example.db_main"
[0m06:56:13.323323 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db_main: BEGIN
[0m06:56:13.323823 [debug] [ThreadPool]: Opening a new connection, currently in state closed
[0m06:56:13.324782 [debug] [ThreadPool]: SQL status: OK in 0.001 seconds
[0m06:56:13.325297 [debug] [ThreadPool]: Using sqlite connection "list_/home/patrick/llm_pricing/example.db_main"
[0m06:56:13.325774 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db_main: /* {"app": "dbt", "dbt_version": "1.9.2", "profile_name": "elasticity_project", "target_name": "dev", "connection_name": "list_/home/patrick/llm_pricing/example.db_main"} */

        pragma database_list
    
[0m06:56:13.326271 [debug] [ThreadPool]: SQL status: OK in 0.000 seconds
[0m06:56:13.328074 [debug] [ThreadPool]: Using sqlite connection "list_/home/patrick/llm_pricing/example.db_main"
[0m06:56:13.328582 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db_main: /* {"app": "dbt", "dbt_version": "1.9.2", "profile_name": "elasticity_project", "target_name": "dev", "connection_name": "list_/home/patrick/llm_pricing/example.db_main"} */

            SELECT
                '/home/patrick/llm_pricing/example.db' as database
                ,name
                ,'main' AS schema
                ,type as data_type
            FROM
                main.sqlite_master
            WHERE
                name NOT LIKE 'sqlite_%'
        
[0m06:56:13.329246 [debug] [ThreadPool]: SQL status: OK in 0.000 seconds
[0m06:56:13.330787 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db_main: ROLLBACK
[0m06:56:13.331269 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db_main: Close
[0m06:56:13.333027 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '29889234-2336-4d96-ab7c-653342c4f262', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71dea0934bc0>]}
[0m06:56:13.334152 [debug] [MainThread]: Using sqlite connection "master"
[0m06:56:13.334950 [debug] [MainThread]: On master: BEGIN
[0m06:56:13.335769 [debug] [MainThread]: Opening a new connection, currently in state init
[0m06:56:13.336829 [debug] [MainThread]: SQL status: OK in 0.001 seconds
[0m06:56:13.337634 [debug] [MainThread]: On master: COMMIT
[0m06:56:13.338446 [debug] [MainThread]: Using sqlite connection "master"
[0m06:56:13.339191 [debug] [MainThread]: On master: COMMIT
[0m06:56:13.339942 [debug] [MainThread]: SQL status: OK in 0.000 seconds
[0m06:56:13.340704 [debug] [MainThread]: On master: Close
[0m06:56:13.343871 [debug] [Thread-1 (]: Began running node model.elasticity_project.costumer_elasticity
[0m06:56:13.344501 [info ] [Thread-1 (]: 1 of 3 START python table model main.costumer_elasticity ....................... [RUN]
[0m06:56:13.345025 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly list_/home/patrick/llm_pricing/example.db_main, now model.elasticity_project.costumer_elasticity)
[0m06:56:13.345547 [debug] [Thread-1 (]: Began compiling node model.elasticity_project.costumer_elasticity
[0m06:56:13.377282 [debug] [Thread-1 (]: Writing injected SQL for node "model.elasticity_project.costumer_elasticity"
[0m06:56:13.378157 [debug] [Thread-1 (]: Began executing node model.elasticity_project.costumer_elasticity
[0m06:56:13.380778 [debug] [Thread-1 (]: Runtime Error in model costumer_elasticity (models/costumer_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m06:56:13.382399 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '29889234-2336-4d96-ab7c-653342c4f262', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71dea0a81460>]}
[0m06:56:13.383066 [error] [Thread-1 (]: 1 of 3 ERROR creating python table model main.costumer_elasticity .............. [[31mERROR[0m in 0.04s]
[0m06:56:13.383824 [debug] [Thread-1 (]: Finished running node model.elasticity_project.costumer_elasticity
[0m06:56:13.384459 [debug] [Thread-1 (]: Began running node model.elasticity_project.customer_product_elasticity
[0m06:56:13.385765 [debug] [Thread-4 (]: Marking all children of 'model.elasticity_project.costumer_elasticity' to be skipped because of status 'error'.  Reason: Runtime Error in model costumer_elasticity (models/costumer_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python".
[0m06:56:13.386928 [info ] [Thread-1 (]: 2 of 3 START python table model main.customer_product_elasticity ............... [RUN]
[0m06:56:13.390037 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly model.elasticity_project.costumer_elasticity, now model.elasticity_project.customer_product_elasticity)
[0m06:56:13.390542 [debug] [Thread-1 (]: Began compiling node model.elasticity_project.customer_product_elasticity
[0m06:56:13.393849 [debug] [Thread-1 (]: Writing injected SQL for node "model.elasticity_project.customer_product_elasticity"
[0m06:56:13.394452 [debug] [Thread-1 (]: Began executing node model.elasticity_project.customer_product_elasticity
[0m06:56:13.396497 [debug] [Thread-1 (]: Runtime Error in model customer_product_elasticity (models/customer_product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m06:56:13.396991 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '29889234-2336-4d96-ab7c-653342c4f262', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71dea0acc290>]}
[0m06:56:13.397653 [error] [Thread-1 (]: 2 of 3 ERROR creating python table model main.customer_product_elasticity ...... [[31mERROR[0m in 0.01s]
[0m06:56:13.398355 [debug] [Thread-1 (]: Finished running node model.elasticity_project.customer_product_elasticity
[0m06:56:13.398831 [debug] [Thread-1 (]: Began running node model.elasticity_project.product_elasticity
[0m06:56:13.399831 [debug] [Thread-4 (]: Marking all children of 'model.elasticity_project.customer_product_elasticity' to be skipped because of status 'error'.  Reason: Runtime Error in model customer_product_elasticity (models/customer_product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python".
[0m06:56:13.400876 [info ] [Thread-1 (]: 3 of 3 START python table model main.product_elasticity ........................ [RUN]
[0m06:56:13.401854 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly model.elasticity_project.customer_product_elasticity, now model.elasticity_project.product_elasticity)
[0m06:56:13.402324 [debug] [Thread-1 (]: Began compiling node model.elasticity_project.product_elasticity
[0m06:56:13.405630 [debug] [Thread-1 (]: Writing injected SQL for node "model.elasticity_project.product_elasticity"
[0m06:56:13.406262 [debug] [Thread-1 (]: Began executing node model.elasticity_project.product_elasticity
[0m06:56:13.408348 [debug] [Thread-1 (]: Runtime Error in model product_elasticity (models/product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m06:56:13.408840 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '29889234-2336-4d96-ab7c-653342c4f262', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71dea0c1c6b0>]}
[0m06:56:13.409548 [error] [Thread-1 (]: 3 of 3 ERROR creating python table model main.product_elasticity ............... [[31mERROR[0m in 0.01s]
[0m06:56:13.410271 [debug] [Thread-1 (]: Finished running node model.elasticity_project.product_elasticity
[0m06:56:13.411362 [debug] [Thread-4 (]: Marking all children of 'model.elasticity_project.product_elasticity' to be skipped because of status 'error'.  Reason: Runtime Error in model product_elasticity (models/product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python".
[0m06:56:13.414088 [debug] [MainThread]: Using sqlite connection "master"
[0m06:56:13.415186 [debug] [MainThread]: On master: BEGIN
[0m06:56:13.416140 [debug] [MainThread]: Opening a new connection, currently in state closed
[0m06:56:13.417474 [debug] [MainThread]: SQL status: OK in 0.001 seconds
[0m06:56:13.418498 [debug] [MainThread]: On master: COMMIT
[0m06:56:13.419523 [debug] [MainThread]: Using sqlite connection "master"
[0m06:56:13.420478 [debug] [MainThread]: On master: COMMIT
[0m06:56:13.421471 [debug] [MainThread]: SQL status: OK in 0.000 seconds
[0m06:56:13.422433 [debug] [MainThread]: On master: Close
[0m06:56:13.423660 [debug] [MainThread]: Connection 'master' was properly closed.
[0m06:56:13.424596 [debug] [MainThread]: Connection 'model.elasticity_project.product_elasticity' was properly closed.
[0m06:56:13.425679 [info ] [MainThread]: 
[0m06:56:13.426680 [info ] [MainThread]: Finished running 3 table models in 0 hours 0 minutes and 0.23 seconds (0.23s).
[0m06:56:13.429485 [debug] [MainThread]: Command end result
[0m06:56:13.476116 [debug] [MainThread]: Wrote artifact WritableManifest to /home/patrick/llm_pricing/target/manifest.json
[0m06:56:13.478478 [debug] [MainThread]: Wrote artifact SemanticManifest to /home/patrick/llm_pricing/target/semantic_manifest.json
[0m06:56:13.487366 [debug] [MainThread]: Wrote artifact RunExecutionResult to /home/patrick/llm_pricing/target/run_results.json
[0m06:56:13.487861 [info ] [MainThread]: 
[0m06:56:13.488470 [info ] [MainThread]: [31mCompleted with 3 errors, 0 partial successes, and 0 warnings:[0m
[0m06:56:13.488992 [info ] [MainThread]: 
[0m06:56:13.489640 [error] [MainThread]:   Runtime Error in model costumer_elasticity (models/costumer_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m06:56:13.490163 [info ] [MainThread]: 
[0m06:56:13.490767 [error] [MainThread]:   Runtime Error in model customer_product_elasticity (models/customer_product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m06:56:13.491306 [info ] [MainThread]: 
[0m06:56:13.491878 [error] [MainThread]:   Runtime Error in model product_elasticity (models/product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m06:56:13.492380 [info ] [MainThread]: 
[0m06:56:13.492907 [info ] [MainThread]: Done. PASS=0 WARN=0 ERROR=3 SKIP=0 TOTAL=3
[0m06:56:13.494107 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 2.0793614, "process_in_blocks": "120", "process_kernel_time": 0.199887, "process_mem_max_rss": "110888", "process_out_blocks": "2560", "process_user_time": 3.428068}
[0m06:56:13.494728 [debug] [MainThread]: Command `dbt run` failed at 06:56:13.494591 after 2.08 seconds
[0m06:56:13.495278 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71dea1d37020>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71dea0b08e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71dea0b09160>]}
[0m06:56:13.495813 [debug] [MainThread]: Flushing usage events
[0m06:56:14.234389 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m07:01:49.734827 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cbe6d9834a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cbe6d0ab800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cbe6d982d50>]}


============================== 07:01:49.738278 | 779a2dae-c752-41ea-aa20-26b62d0e88ce ==============================
[0m07:01:49.738278 [info ] [MainThread]: Running with dbt=1.9.2
[0m07:01:49.738979 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/patrick/llm_pricing', 'version_check': 'True', 'fail_fast': 'False', 'log_path': '/home/patrick/llm_pricing/logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m07:01:49.903581 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '779a2dae-c752-41ea-aa20-26b62d0e88ce', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cbe6cea7ce0>]}
[0m07:01:49.990669 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '779a2dae-c752-41ea-aa20-26b62d0e88ce', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cbe6d3767e0>]}
[0m07:01:49.991544 [info ] [MainThread]: Registered adapter: sqlite=1.9.0
[0m07:01:50.082585 [debug] [MainThread]: checksum: 12b12750b70de726cfd89136b8e24afc3f3e77597a97bff40ab7e5f9b39d5e18, vars: {}, profile: , target: , version: 1.9.2
[0m07:01:50.175351 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m07:01:50.175905 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '779a2dae-c752-41ea-aa20-26b62d0e88ce', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cbe6cee89b0>]}
[0m07:01:51.397170 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.elasticity_project.models
[0m07:01:51.410011 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '779a2dae-c752-41ea-aa20-26b62d0e88ce', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cbe6c753590>]}
[0m07:01:51.480819 [debug] [MainThread]: Wrote artifact WritableManifest to /home/patrick/llm_pricing/target/manifest.json
[0m07:01:51.483530 [debug] [MainThread]: Wrote artifact SemanticManifest to /home/patrick/llm_pricing/target/semantic_manifest.json
[0m07:01:51.551018 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '779a2dae-c752-41ea-aa20-26b62d0e88ce', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cbe6d37f7a0>]}
[0m07:01:51.551651 [info ] [MainThread]: Found 3 models, 1 source, 413 macros
[0m07:01:51.552165 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '779a2dae-c752-41ea-aa20-26b62d0e88ce', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cbe6f00d100>]}
[0m07:01:51.554038 [info ] [MainThread]: 
[0m07:01:51.554484 [info ] [MainThread]: Concurrency: 1 threads (target='dev')
[0m07:01:51.554872 [info ] [MainThread]: 
[0m07:01:51.555476 [debug] [MainThread]: Acquiring new sqlite connection 'master'
[0m07:01:51.561594 [debug] [ThreadPool]: Acquiring new sqlite connection 'list_/home/patrick/llm_pricing/example.db'
[0m07:01:51.607404 [debug] [ThreadPool]: Using sqlite connection "list_/home/patrick/llm_pricing/example.db"
[0m07:01:51.607894 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db: BEGIN
[0m07:01:51.608280 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m07:01:51.608980 [debug] [ThreadPool]: SQL status: OK in 0.001 seconds
[0m07:01:51.609350 [debug] [ThreadPool]: Using sqlite connection "list_/home/patrick/llm_pricing/example.db"
[0m07:01:51.609851 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db: /* {"app": "dbt", "dbt_version": "1.9.2", "profile_name": "elasticity_project", "target_name": "dev", "connection_name": "list_/home/patrick/llm_pricing/example.db"} */

        pragma database_list
    
[0m07:01:51.610564 [debug] [ThreadPool]: SQL status: OK in 0.000 seconds
[0m07:01:51.612384 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db: ROLLBACK
[0m07:01:51.612870 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db: Close
[0m07:01:51.614761 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_/home/patrick/llm_pricing/example.db, now list_/home/patrick/llm_pricing/example.db_main)
[0m07:01:51.626420 [debug] [ThreadPool]: Using sqlite connection "list_/home/patrick/llm_pricing/example.db_main"
[0m07:01:51.626938 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db_main: BEGIN
[0m07:01:51.627420 [debug] [ThreadPool]: Opening a new connection, currently in state closed
[0m07:01:51.628097 [debug] [ThreadPool]: SQL status: OK in 0.001 seconds
[0m07:01:51.628583 [debug] [ThreadPool]: Using sqlite connection "list_/home/patrick/llm_pricing/example.db_main"
[0m07:01:51.629050 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db_main: /* {"app": "dbt", "dbt_version": "1.9.2", "profile_name": "elasticity_project", "target_name": "dev", "connection_name": "list_/home/patrick/llm_pricing/example.db_main"} */

        pragma database_list
    
[0m07:01:51.629559 [debug] [ThreadPool]: SQL status: OK in 0.000 seconds
[0m07:01:51.631319 [debug] [ThreadPool]: Using sqlite connection "list_/home/patrick/llm_pricing/example.db_main"
[0m07:01:51.631817 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db_main: /* {"app": "dbt", "dbt_version": "1.9.2", "profile_name": "elasticity_project", "target_name": "dev", "connection_name": "list_/home/patrick/llm_pricing/example.db_main"} */

            SELECT
                '/home/patrick/llm_pricing/example.db' as database
                ,name
                ,'main' AS schema
                ,type as data_type
            FROM
                main.sqlite_master
            WHERE
                name NOT LIKE 'sqlite_%'
        
[0m07:01:51.632501 [debug] [ThreadPool]: SQL status: OK in 0.000 seconds
[0m07:01:51.633945 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db_main: ROLLBACK
[0m07:01:51.634430 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db_main: Close
[0m07:01:51.635845 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '779a2dae-c752-41ea-aa20-26b62d0e88ce', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cbe6c7dbe30>]}
[0m07:01:51.636650 [debug] [MainThread]: Using sqlite connection "master"
[0m07:01:51.637285 [debug] [MainThread]: On master: BEGIN
[0m07:01:51.637880 [debug] [MainThread]: Opening a new connection, currently in state init
[0m07:01:51.638702 [debug] [MainThread]: SQL status: OK in 0.001 seconds
[0m07:01:51.639335 [debug] [MainThread]: On master: COMMIT
[0m07:01:51.639957 [debug] [MainThread]: Using sqlite connection "master"
[0m07:01:51.640572 [debug] [MainThread]: On master: COMMIT
[0m07:01:51.641210 [debug] [MainThread]: SQL status: OK in 0.000 seconds
[0m07:01:51.641820 [debug] [MainThread]: On master: Close
[0m07:01:51.644443 [debug] [Thread-1 (]: Began running node model.elasticity_project.costumer_elasticity
[0m07:01:51.645289 [info ] [Thread-1 (]: 1 of 3 START python table model main.costumer_elasticity ....................... [RUN]
[0m07:01:51.645801 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly list_/home/patrick/llm_pricing/example.db_main, now model.elasticity_project.costumer_elasticity)
[0m07:01:51.646254 [debug] [Thread-1 (]: Began compiling node model.elasticity_project.costumer_elasticity
[0m07:01:51.676499 [debug] [Thread-1 (]: Writing injected SQL for node "model.elasticity_project.costumer_elasticity"
[0m07:01:51.677289 [debug] [Thread-1 (]: Began executing node model.elasticity_project.costumer_elasticity
[0m07:01:51.679803 [debug] [Thread-1 (]: Runtime Error in model costumer_elasticity (models/costumer_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m07:01:51.681409 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '779a2dae-c752-41ea-aa20-26b62d0e88ce', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cbe6c65cfe0>]}
[0m07:01:51.682148 [error] [Thread-1 (]: 1 of 3 ERROR creating python table model main.costumer_elasticity .............. [[31mERROR[0m in 0.03s]
[0m07:01:51.682977 [debug] [Thread-1 (]: Finished running node model.elasticity_project.costumer_elasticity
[0m07:01:51.683520 [debug] [Thread-1 (]: Began running node model.elasticity_project.customer_product_elasticity
[0m07:01:51.684074 [info ] [Thread-1 (]: 2 of 3 START python table model main.customer_product_elasticity ............... [RUN]
[0m07:01:51.685240 [debug] [Thread-4 (]: Marking all children of 'model.elasticity_project.costumer_elasticity' to be skipped because of status 'error'.  Reason: Runtime Error in model costumer_elasticity (models/costumer_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python".
[0m07:01:51.686243 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly model.elasticity_project.costumer_elasticity, now model.elasticity_project.customer_product_elasticity)
[0m07:01:51.689034 [debug] [Thread-1 (]: Began compiling node model.elasticity_project.customer_product_elasticity
[0m07:01:51.692216 [debug] [Thread-1 (]: Writing injected SQL for node "model.elasticity_project.customer_product_elasticity"
[0m07:01:51.692941 [debug] [Thread-1 (]: Began executing node model.elasticity_project.customer_product_elasticity
[0m07:01:51.695346 [debug] [Thread-1 (]: Runtime Error in model customer_product_elasticity (models/customer_product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m07:01:51.695905 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '779a2dae-c752-41ea-aa20-26b62d0e88ce', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cbe6c2c13d0>]}
[0m07:01:51.696575 [error] [Thread-1 (]: 2 of 3 ERROR creating python table model main.customer_product_elasticity ...... [[31mERROR[0m in 0.01s]
[0m07:01:51.697271 [debug] [Thread-1 (]: Finished running node model.elasticity_project.customer_product_elasticity
[0m07:01:51.697733 [debug] [Thread-1 (]: Began running node model.elasticity_project.product_elasticity
[0m07:01:51.698244 [info ] [Thread-1 (]: 3 of 3 START python table model main.product_elasticity ........................ [RUN]
[0m07:01:51.698724 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly model.elasticity_project.customer_product_elasticity, now model.elasticity_project.product_elasticity)
[0m07:01:51.699157 [debug] [Thread-1 (]: Began compiling node model.elasticity_project.product_elasticity
[0m07:01:51.702865 [debug] [Thread-1 (]: Writing injected SQL for node "model.elasticity_project.product_elasticity"
[0m07:01:51.703947 [debug] [Thread-4 (]: Marking all children of 'model.elasticity_project.customer_product_elasticity' to be skipped because of status 'error'.  Reason: Runtime Error in model customer_product_elasticity (models/customer_product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python".
[0m07:01:51.705431 [debug] [Thread-1 (]: Began executing node model.elasticity_project.product_elasticity
[0m07:01:51.707652 [debug] [Thread-1 (]: Runtime Error in model product_elasticity (models/product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m07:01:51.708142 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '779a2dae-c752-41ea-aa20-26b62d0e88ce', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cbe6b909280>]}
[0m07:01:51.708810 [error] [Thread-1 (]: 3 of 3 ERROR creating python table model main.product_elasticity ............... [[31mERROR[0m in 0.01s]
[0m07:01:51.709554 [debug] [Thread-1 (]: Finished running node model.elasticity_project.product_elasticity
[0m07:01:51.710596 [debug] [Thread-4 (]: Marking all children of 'model.elasticity_project.product_elasticity' to be skipped because of status 'error'.  Reason: Runtime Error in model product_elasticity (models/product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python".
[0m07:01:51.713308 [debug] [MainThread]: Using sqlite connection "master"
[0m07:01:51.714180 [debug] [MainThread]: On master: BEGIN
[0m07:01:51.714945 [debug] [MainThread]: Opening a new connection, currently in state closed
[0m07:01:51.716063 [debug] [MainThread]: SQL status: OK in 0.001 seconds
[0m07:01:51.716868 [debug] [MainThread]: On master: COMMIT
[0m07:01:51.717664 [debug] [MainThread]: Using sqlite connection "master"
[0m07:01:51.718454 [debug] [MainThread]: On master: COMMIT
[0m07:01:51.719271 [debug] [MainThread]: SQL status: OK in 0.000 seconds
[0m07:01:51.720028 [debug] [MainThread]: On master: Close
[0m07:01:51.720988 [debug] [MainThread]: Connection 'master' was properly closed.
[0m07:01:51.721770 [debug] [MainThread]: Connection 'model.elasticity_project.product_elasticity' was properly closed.
[0m07:01:51.722680 [info ] [MainThread]: 
[0m07:01:51.723536 [info ] [MainThread]: Finished running 3 table models in 0 hours 0 minutes and 0.17 seconds (0.17s).
[0m07:01:51.725904 [debug] [MainThread]: Command end result
[0m07:01:51.763032 [debug] [MainThread]: Wrote artifact WritableManifest to /home/patrick/llm_pricing/target/manifest.json
[0m07:01:51.765359 [debug] [MainThread]: Wrote artifact SemanticManifest to /home/patrick/llm_pricing/target/semantic_manifest.json
[0m07:01:51.774577 [debug] [MainThread]: Wrote artifact RunExecutionResult to /home/patrick/llm_pricing/target/run_results.json
[0m07:01:51.775088 [info ] [MainThread]: 
[0m07:01:51.775713 [info ] [MainThread]: [31mCompleted with 3 errors, 0 partial successes, and 0 warnings:[0m
[0m07:01:51.776274 [info ] [MainThread]: 
[0m07:01:51.776921 [error] [MainThread]:   Runtime Error in model costumer_elasticity (models/costumer_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m07:01:51.777576 [info ] [MainThread]: 
[0m07:01:51.778197 [error] [MainThread]:   Runtime Error in model customer_product_elasticity (models/customer_product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m07:01:51.778662 [info ] [MainThread]: 
[0m07:01:51.779206 [error] [MainThread]:   Runtime Error in model product_elasticity (models/product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m07:01:51.779658 [info ] [MainThread]: 
[0m07:01:51.780172 [info ] [MainThread]: Done. PASS=0 WARN=0 ERROR=3 SKIP=0 TOTAL=3
[0m07:01:51.781408 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 2.1217387, "process_in_blocks": "0", "process_kernel_time": 0.211765, "process_mem_max_rss": "109600", "process_out_blocks": "2560", "process_user_time": 3.468156}
[0m07:01:51.782049 [debug] [MainThread]: Command `dbt run` failed at 07:01:51.781914 after 2.12 seconds
[0m07:01:51.782584 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cbe6d0ab800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cbe6c9a9a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7cbe6db1cf20>]}
[0m07:01:51.783090 [debug] [MainThread]: Flushing usage events
[0m07:01:52.598344 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m07:06:47.630334 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a72e2f47530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a72e3489f40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a72e2f46300>]}


============================== 07:06:47.633869 | cd330adc-9fc4-4cab-b152-0b4bf893ba80 ==============================
[0m07:06:47.633869 [info ] [MainThread]: Running with dbt=1.9.2
[0m07:06:47.635175 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/home/patrick/llm_pricing', 'log_path': '/home/patrick/llm_pricing/logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m07:06:47.802143 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'cd330adc-9fc4-4cab-b152-0b4bf893ba80', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a72e2cbbe90>]}
[0m07:06:47.889009 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'cd330adc-9fc4-4cab-b152-0b4bf893ba80', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a72e34c2660>]}
[0m07:06:47.889867 [info ] [MainThread]: Registered adapter: sqlite=1.9.0
[0m07:06:47.980176 [debug] [MainThread]: checksum: 12b12750b70de726cfd89136b8e24afc3f3e77597a97bff40ab7e5f9b39d5e18, vars: {}, profile: , target: , version: 1.9.2
[0m07:06:48.070616 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m07:06:48.071196 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'cd330adc-9fc4-4cab-b152-0b4bf893ba80', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a72e2cf0680>]}
[0m07:06:49.348463 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.elasticity_project.models
[0m07:06:49.362868 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'cd330adc-9fc4-4cab-b152-0b4bf893ba80', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a72e2621160>]}
[0m07:06:49.433928 [debug] [MainThread]: Wrote artifact WritableManifest to /home/patrick/llm_pricing/target/manifest.json
[0m07:06:49.436576 [debug] [MainThread]: Wrote artifact SemanticManifest to /home/patrick/llm_pricing/target/semantic_manifest.json
[0m07:06:49.505863 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'cd330adc-9fc4-4cab-b152-0b4bf893ba80', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a72e4e582c0>]}
[0m07:06:49.506463 [info ] [MainThread]: Found 3 models, 1 source, 413 macros
[0m07:06:49.506919 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'cd330adc-9fc4-4cab-b152-0b4bf893ba80', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a72e470af00>]}
[0m07:06:49.508876 [info ] [MainThread]: 
[0m07:06:49.509340 [info ] [MainThread]: Concurrency: 1 threads (target='dev')
[0m07:06:49.509724 [info ] [MainThread]: 
[0m07:06:49.510283 [debug] [MainThread]: Acquiring new sqlite connection 'master'
[0m07:06:49.516190 [debug] [ThreadPool]: Acquiring new sqlite connection 'list_/home/patrick/llm_pricing/example.db'
[0m07:06:49.565364 [debug] [ThreadPool]: Using sqlite connection "list_/home/patrick/llm_pricing/example.db"
[0m07:06:49.566242 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db: BEGIN
[0m07:06:49.566955 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m07:06:49.568263 [debug] [ThreadPool]: SQL status: OK in 0.001 seconds
[0m07:06:49.568962 [debug] [ThreadPool]: Using sqlite connection "list_/home/patrick/llm_pricing/example.db"
[0m07:06:49.569423 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db: /* {"app": "dbt", "dbt_version": "1.9.2", "profile_name": "elasticity_project", "target_name": "dev", "connection_name": "list_/home/patrick/llm_pricing/example.db"} */

        pragma database_list
    
[0m07:06:49.569859 [debug] [ThreadPool]: SQL status: OK in 0.000 seconds
[0m07:06:49.571360 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db: ROLLBACK
[0m07:06:49.571781 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db: Close
[0m07:06:49.573873 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_/home/patrick/llm_pricing/example.db, now list_/home/patrick/llm_pricing/example.db_main)
[0m07:06:49.584844 [debug] [ThreadPool]: Using sqlite connection "list_/home/patrick/llm_pricing/example.db_main"
[0m07:06:49.585366 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db_main: BEGIN
[0m07:06:49.585845 [debug] [ThreadPool]: Opening a new connection, currently in state closed
[0m07:06:49.586492 [debug] [ThreadPool]: SQL status: OK in 0.001 seconds
[0m07:06:49.586939 [debug] [ThreadPool]: Using sqlite connection "list_/home/patrick/llm_pricing/example.db_main"
[0m07:06:49.587389 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db_main: /* {"app": "dbt", "dbt_version": "1.9.2", "profile_name": "elasticity_project", "target_name": "dev", "connection_name": "list_/home/patrick/llm_pricing/example.db_main"} */

        pragma database_list
    
[0m07:06:49.587846 [debug] [ThreadPool]: SQL status: OK in 0.000 seconds
[0m07:06:49.589455 [debug] [ThreadPool]: Using sqlite connection "list_/home/patrick/llm_pricing/example.db_main"
[0m07:06:49.589917 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db_main: /* {"app": "dbt", "dbt_version": "1.9.2", "profile_name": "elasticity_project", "target_name": "dev", "connection_name": "list_/home/patrick/llm_pricing/example.db_main"} */

            SELECT
                '/home/patrick/llm_pricing/example.db' as database
                ,name
                ,'main' AS schema
                ,type as data_type
            FROM
                main.sqlite_master
            WHERE
                name NOT LIKE 'sqlite_%'
        
[0m07:06:49.590591 [debug] [ThreadPool]: SQL status: OK in 0.000 seconds
[0m07:06:49.591947 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db_main: ROLLBACK
[0m07:06:49.592450 [debug] [ThreadPool]: On list_/home/patrick/llm_pricing/example.db_main: Close
[0m07:06:49.593790 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'cd330adc-9fc4-4cab-b152-0b4bf893ba80', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a72e24820f0>]}
[0m07:06:49.594432 [debug] [MainThread]: Using sqlite connection "master"
[0m07:06:49.594893 [debug] [MainThread]: On master: BEGIN
[0m07:06:49.595355 [debug] [MainThread]: Opening a new connection, currently in state init
[0m07:06:49.595979 [debug] [MainThread]: SQL status: OK in 0.001 seconds
[0m07:06:49.596449 [debug] [MainThread]: On master: COMMIT
[0m07:06:49.596905 [debug] [MainThread]: Using sqlite connection "master"
[0m07:06:49.597362 [debug] [MainThread]: On master: COMMIT
[0m07:06:49.597823 [debug] [MainThread]: SQL status: OK in 0.000 seconds
[0m07:06:49.598344 [debug] [MainThread]: On master: Close
[0m07:06:49.600892 [debug] [Thread-1 (]: Began running node model.elasticity_project.costumer_elasticity
[0m07:06:49.601756 [info ] [Thread-1 (]: 1 of 3 START python table model main.costumer_elasticity ....................... [RUN]
[0m07:06:49.602548 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly list_/home/patrick/llm_pricing/example.db_main, now model.elasticity_project.costumer_elasticity)
[0m07:06:49.603296 [debug] [Thread-1 (]: Began compiling node model.elasticity_project.costumer_elasticity
[0m07:06:49.634342 [debug] [Thread-1 (]: Writing injected SQL for node "model.elasticity_project.costumer_elasticity"
[0m07:06:49.635142 [debug] [Thread-1 (]: Began executing node model.elasticity_project.costumer_elasticity
[0m07:06:49.637923 [debug] [Thread-1 (]: Runtime Error in model costumer_elasticity (models/costumer_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m07:06:49.639761 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'cd330adc-9fc4-4cab-b152-0b4bf893ba80', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a72e25e7b30>]}
[0m07:06:49.640537 [error] [Thread-1 (]: 1 of 3 ERROR creating python table model main.costumer_elasticity .............. [[31mERROR[0m in 0.04s]
[0m07:06:49.641431 [debug] [Thread-1 (]: Finished running node model.elasticity_project.costumer_elasticity
[0m07:06:49.641964 [debug] [Thread-1 (]: Began running node model.elasticity_project.customer_product_elasticity
[0m07:06:49.642579 [info ] [Thread-1 (]: 2 of 3 START python table model main.customer_product_elasticity ............... [RUN]
[0m07:06:49.643328 [debug] [Thread-4 (]: Marking all children of 'model.elasticity_project.costumer_elasticity' to be skipped because of status 'error'.  Reason: Runtime Error in model costumer_elasticity (models/costumer_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python".
[0m07:06:49.643931 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly model.elasticity_project.costumer_elasticity, now model.elasticity_project.customer_product_elasticity)
[0m07:06:49.645643 [debug] [Thread-1 (]: Began compiling node model.elasticity_project.customer_product_elasticity
[0m07:06:49.649230 [debug] [Thread-1 (]: Writing injected SQL for node "model.elasticity_project.customer_product_elasticity"
[0m07:06:49.649911 [debug] [Thread-1 (]: Began executing node model.elasticity_project.customer_product_elasticity
[0m07:06:49.652075 [debug] [Thread-1 (]: Runtime Error in model customer_product_elasticity (models/customer_product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m07:06:49.652623 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'cd330adc-9fc4-4cab-b152-0b4bf893ba80', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a72e1879100>]}
[0m07:06:49.653304 [error] [Thread-1 (]: 2 of 3 ERROR creating python table model main.customer_product_elasticity ...... [[31mERROR[0m in 0.01s]
[0m07:06:49.654350 [debug] [Thread-1 (]: Finished running node model.elasticity_project.customer_product_elasticity
[0m07:06:49.655163 [debug] [Thread-1 (]: Began running node model.elasticity_project.product_elasticity
[0m07:06:49.655910 [debug] [Thread-4 (]: Marking all children of 'model.elasticity_project.customer_product_elasticity' to be skipped because of status 'error'.  Reason: Runtime Error in model customer_product_elasticity (models/customer_product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python".
[0m07:06:49.656577 [info ] [Thread-1 (]: 3 of 3 START python table model main.product_elasticity ........................ [RUN]
[0m07:06:49.657357 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly model.elasticity_project.customer_product_elasticity, now model.elasticity_project.product_elasticity)
[0m07:06:49.657823 [debug] [Thread-1 (]: Began compiling node model.elasticity_project.product_elasticity
[0m07:06:49.661258 [debug] [Thread-1 (]: Writing injected SQL for node "model.elasticity_project.product_elasticity"
[0m07:06:49.661869 [debug] [Thread-1 (]: Began executing node model.elasticity_project.product_elasticity
[0m07:06:49.663908 [debug] [Thread-1 (]: Runtime Error in model product_elasticity (models/product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m07:06:49.664410 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'cd330adc-9fc4-4cab-b152-0b4bf893ba80', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a72e18fd5e0>]}
[0m07:06:49.665052 [error] [Thread-1 (]: 3 of 3 ERROR creating python table model main.product_elasticity ............... [[31mERROR[0m in 0.01s]
[0m07:06:49.665870 [debug] [Thread-1 (]: Finished running node model.elasticity_project.product_elasticity
[0m07:06:49.666548 [debug] [Thread-4 (]: Marking all children of 'model.elasticity_project.product_elasticity' to be skipped because of status 'error'.  Reason: Runtime Error in model product_elasticity (models/product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python".
[0m07:06:49.667968 [debug] [MainThread]: Using sqlite connection "master"
[0m07:06:49.668458 [debug] [MainThread]: On master: BEGIN
[0m07:06:49.668893 [debug] [MainThread]: Opening a new connection, currently in state closed
[0m07:06:49.669540 [debug] [MainThread]: SQL status: OK in 0.001 seconds
[0m07:06:49.670010 [debug] [MainThread]: On master: COMMIT
[0m07:06:49.670477 [debug] [MainThread]: Using sqlite connection "master"
[0m07:06:49.670907 [debug] [MainThread]: On master: COMMIT
[0m07:06:49.671380 [debug] [MainThread]: SQL status: OK in 0.000 seconds
[0m07:06:49.671840 [debug] [MainThread]: On master: Close
[0m07:06:49.672406 [debug] [MainThread]: Connection 'master' was properly closed.
[0m07:06:49.672811 [debug] [MainThread]: Connection 'model.elasticity_project.product_elasticity' was properly closed.
[0m07:06:49.673322 [info ] [MainThread]: 
[0m07:06:49.673792 [info ] [MainThread]: Finished running 3 table models in 0 hours 0 minutes and 0.16 seconds (0.16s).
[0m07:06:49.675160 [debug] [MainThread]: Command end result
[0m07:06:49.712459 [debug] [MainThread]: Wrote artifact WritableManifest to /home/patrick/llm_pricing/target/manifest.json
[0m07:06:49.714894 [debug] [MainThread]: Wrote artifact SemanticManifest to /home/patrick/llm_pricing/target/semantic_manifest.json
[0m07:06:49.723913 [debug] [MainThread]: Wrote artifact RunExecutionResult to /home/patrick/llm_pricing/target/run_results.json
[0m07:06:49.724491 [info ] [MainThread]: 
[0m07:06:49.725135 [info ] [MainThread]: [31mCompleted with 3 errors, 0 partial successes, and 0 warnings:[0m
[0m07:06:49.725705 [info ] [MainThread]: 
[0m07:06:49.726399 [error] [MainThread]:   Runtime Error in model costumer_elasticity (models/costumer_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m07:06:49.726935 [info ] [MainThread]: 
[0m07:06:49.727586 [error] [MainThread]:   Runtime Error in model customer_product_elasticity (models/customer_product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m07:06:49.728108 [info ] [MainThread]: 
[0m07:06:49.728744 [error] [MainThread]:   Runtime Error in model product_elasticity (models/product_elasticity.py)
  Materialization "materialization_table_sqlite" only supports languages ['sql']; got "python"
[0m07:06:49.729273 [info ] [MainThread]: 
[0m07:06:49.729832 [info ] [MainThread]: Done. PASS=0 WARN=0 ERROR=3 SKIP=0 TOTAL=3
[0m07:06:49.731046 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 2.1803303, "process_in_blocks": "0", "process_kernel_time": 0.183948, "process_mem_max_rss": "109124", "process_out_blocks": "2560", "process_user_time": 3.565998}
[0m07:06:49.731697 [debug] [MainThread]: Command `dbt run` failed at 07:06:49.731562 after 2.18 seconds
[0m07:06:49.732256 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a72e4b35a60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a72e26fd2b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a72e3907350>]}
[0m07:06:49.732816 [debug] [MainThread]: Flushing usage events
[0m07:06:50.497802 [debug] [MainThread]: An error was encountered while trying to flush usage events
